import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/styles/globals.css';

const tele2TextSansRegular = localFont({
	src: '../../public/fonts/Tele2TextSansWebRegular.woff',
	variable: '--font-tele2',
	style: 'regular',
});

const tele2TextSansBold = localFont({
	src: '../../public/fonts/Tele2TextSansWebBold.woff',
	variable: '--font-tele2',
	style: 'bold',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${tele2TextSansRegular.className} ${tele2TextSansBold.className}`}>
				{children}
			</body>
		</html>
	);
}
